version: '3'
services:
  spark-master:
    image: apache/spark:latest 
    container_name: spark-master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8080:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    networks:
    - spark_cluster


  spark-worker-1:
    image: apache/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

    networks:
      - spark_cluster

networks:
  spark_cluster:
    external: true
